x=int(input('Planlanmış üretim süresini giriniz:'))
y=int(input('Plansız duruşu giriniz:'))
z=int(input('Standart çevrim zamanını giriniz:'))
a=int(input('Üretim miktarını giriniz:'))
b=int(input('Sağlam ürün miktarını giriniz:'))
c=int(input('Toplam üretim miktarını giriniz:'))

kullanilabilirlik=((x-y)/x)
performans=((z*a)/(x-y))
kalite=(b/c)
EkipmanEtkililikOrani=((kullanilabilirlik*performans*kalite)*100)
print (EkipmanEtkililikOrani)